services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - ARTIFACT_BASE_URL=http://localhost:8000/artifacts

  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.webapp
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
